### ISSUE TITLE
Deconst 500 error - unable to ping registry endpoint

### ISSUE THREAD

**Issue by meker12** [deconst/client#36]
I am getting this error in the client periodically.  It seems to happen when I change content and the client rebuilds it.  If I run > docker-machine restart deconst-client,  the client comes back and works fine again.

![deconst-500-error](https://cloud.githubusercontent.com/assets/6391769/9942497/f1e8dc78-5d40-11e5-890a-03cf78cddf07.png)

**Comment by smashwilson** [comment]
Interesting. This looks like a problem with quay.io - it's serving a 500 when we try to pull a new container image.

I should make the client more robust to quay not being available.

**Comment by meker12** [comment]
Oh -- here's some interesting info about quay.io and Docker:  http://docs.quay.io/issues/odd-login-failure.html

There is also a link to a possible fix for VB and errors caused by network delays here: https://github.com/mitchellh/vagrant/issues/1807.

**Comment by meker12** [comment]
Constanze is also getting the same error on her MacBook Air with OS X version 10.10.  I
