### ISSUE TITLE
Is there a way to view Sphinx preparer build output from the local deconst-client build?

### ISSUE THREAD

**Issue by meker12** [deconst/client#47]
Maybe this is in the deconst-client documentation,  but if I wanted to see the output of the build to see if there are Sphinx errors,  where/how can I check that  -- in the deconst-client container logs?

I can always build locally with Sphinx, but if I bypassed that step and only use deconst, would like to see the build output to troubleshoot problems in navigation or content that might be a result of "non-severe" Sphinx errors.

**Comment by smashwilson** [comment]
There is indeed, through docker-machine and the docker CLI. I've got a brief [section in the README](https://github.com/deconst/client#inspecting-docker-containers) about it, but basically it's:

``` bash
# Set environment variables so that "docker" talks to the Deconst client VM in this terminal
eval "$(docker-machine env deconst-client)"

# See which containers are running.
docker ps -a

# The container you're looking for is called "preparer-content-<some number>".
# There isn't a *great* way to tell which one is which if you have a few repositories active; you
# can trigger a change and then see which one starts up again, for example.

# Once you know which container is yours, you can watch the output live with:
docker logs -f preparer-content-<some number>

# Just leave off the "-f" after the build is finished to see the full Sphinx log.
```

**Comment by meker12** [comment]
Awesome!
